### ISSUE TITLE
GNU Radio Companion crashing on Mac

### ISSUE THREAD

**Issue by DavidPowell** [conda-forge/gnuradio-feedstock#114]
I am using GNU Radio Companion in a class I run, where students are creating a clean Python 3.9 conda environment, and installing the latest stable GNU radio build from this conda channel.

A few of my students are using Macs (I believe mostly older Intel Macs), and all except 1 of them reported that Gnu Radio companion crashes on startup (as a workaround they are using shared Windows PCs, which have no problems). One of them was able to provide the following [error message](https://github.com/conda-forge/gnuradio-feedstock/files/8158011/error.message.txt).
 
Please advise if there is any additional information I can gather to help resolve this issue (I do not have a Mac myself, so this may take some time).

**Comment by ryanvolz** [comment]
Thanks for the report. I've heard mention of possible crashes on macOS, but this is the best sample size yet. I'm also not a mac user, so I don't have any means to do direct testing.

You say it works for one person. Is there anything notably different about their system? Maybe a particular OS version, or they're the only one that does/doesn't have a high-DPI display?

Another data point the would definitely be helpful, if any of the students are willing, is to see if any other versions work. Try `gnuradio` 3.8, 3.9, and 3.10, but also older builds within those series (going back in time as much as possible, e.g 3.9.0.0). If they find a version that works, that could help pinpoint a change in the recipe or a dependency that causes this problem.

Similarly, they could try installing GNU Radio via other methods (Homebrew, MacPorts) and see if those crash as well. This is probably less important, because I suspect that they will find that they do not crash and that this is therefore specific to the conda build.

**Comment by DavidPowell** [comment]
One student managed to install via homebrew, and found that this version did not crash.

I will ask them to install earlier versions of the conda package, and report back.

**Comment by DavidPowell** [comment]
Correcting my previous statement, all students with Macs found that GNU Radio Companion crashed when installed from conda (at least 5 of them).

Students have used conda to install versions 3.8.5.0 and 3.9.5.0, but the crash still occurs.

**Comment by ryanvolz** [comment]
Thanks David. I think we can assume that it's not GRC itself that is the problem on macOS, but something different about the `gtk3` stack on conda-forge results in the crash. Perusing the GTK3 Gitlab repository, it seems like support for macOS with the Quartz backend is something that tends to break because not many developers are using it or testing it, so I suppose this is not surprising.

I will try to do some comparisons with Homebrew to see if they patch anything or use a particular version that makes it work.

I think I'll also plan on doing a build of `gnuradio` that is compatible with all of the versions of `gtk3` available on conda-forge, so that I can ask people to test with the different versions of `gtk3` and see if any of the older ones work.

**Comment by ryanvolz** [comment]
I have uploaded a build for GNU Radio 3.10.1.1 on macOS that allows for using different GTK versions. The students can install it with different `gtk3` packages using
```
conda install -c ryanvolz -c conda-forge --no-channel-priority gnuradio=3.10.1.1.dev0 gtk3=VER
```
where `VER` is a `gtk3` version from the following list:

- 3.24.14
- 3.24.18
- 3.24.20
- 3.24.21
- 3.24.22
- 3.24.23
- 3.24.24
- 3.24.25
- 3.24.26
- 3.24.27
- 3.24.28
- 3.24.29
- 3.24.31 (most recent, which we know causes crashes)

Maybe one of those `gtk3` versions will allow it to work.

If not `gtk3`, then maybe different versions of `pygobject`, or `glib` would be worth trying.

**Comment by ryanvolz** [comment]
A patch for `cairo` was just merged that fixes a known crash on macOS 11.6+. Maybe that accounts for the crashes reported here?

**Comment by ryanvolz** [comment]
I'm going to assume this was either the GRC cairo issues fixed by https://github.com/gnuradio/gnuradio/pull/6352 or the Python block crashing fixed by https://github.com/gnuradio/gnuradio/issues/6283. Probably the latter?

**Comment by DavidPowell** [comment]
Thanks for looking into this. Unfortunately I have not been able to get feedback from Mac users to confirm whether or not the issue has been resolved. I will comment on this issue if I get any further information on this issue, but I agree it makes sense to close at this point.
