### ISSUE TITLE
Request: Add gr-m2k

### ISSUE THREAD

**Issue by Modiug** [conda-forge/gnuradio-feedstock#155]
The ADALM2000 is a similar to the PLUTO, but needs a different Gnuradio module.
Could you please integrate gr-m2k [https://wiki.analog.com/university/tools/m2k/libm2k/gr-m2k](https://wiki.analog.com/university/tools/m2k/libm2k/gr-m2k)?
It's probably trivial to include, but I am not familiar with the Conda gnuradio-feedstock setup.

**Comment by ryanvolz** [comment]
Thanks for the report. Without having tried to build it or make a recipe, I see two potential blockers for making a `gr-m2k` conda-forge package (but that's not saying it won't happen):
1. Currently, it only appears to be compatible with GNU Radio 3.8. I'd probably want compatibility with 3.10 to keep up with the rest of the ecosystem, although it's not a blocker.
2. Conda-forge requires that packages have a versioned release, and so far that is not true for `gr-m2k`. The only way around that is to make a release, or host the package on a personal anaconda.org channel instead of through conda-forge. (This is a problem for many GNU Radio OOT modules, for what it's worth.)

If you're motivated to speed this up, put in a kind word with the developers of `gr-m2k` to see if they would be willing to add support for GR 3.10 and make a release. Thanks!

**Comment by Modiug** [comment]
Thanks Ryan, I opened an issue with gr-m2k (https://github.com/analogdevicesinc/gr-m2k/issues/22).
But activities are quite low over there. Let's see...

**Comment by AlexandraTrifan** [comment]
Hi,

We have created a release tag for the first official release version of gr-m2k. This one is GNU Radio 3.10 compatible.
The **maint-3.8** branch is 3.8 compatible.
Is this what was needed in order to start the integration of gr-m2k?

Thank you!
-Alexandra

**Comment by ryanvolz** [comment]
PR to add gr-m2k to conda-forge: https://github.com/conda-forge/staged-recipes/pull/21170

**Comment by ryanvolz** [comment]
Now available at https://github.com/conda-forge/gnuradio-m2k-feedstock.
